name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install the latest version of uv and activate the environment
      uses: astral-sh/setup-uv@v6
      with:
        activate-environment: true

    - name: Install dependencies
      run: |
        uv sync
        uv pip install --system --upgrade pip
        uv pip install pip
        uv pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
